### ISSUE TITLE
Harvest Info

### ISSUE THREAD

**Issue by AnthonyLaw** [nemtech/symbol-openapi#106]
I would like to propose add new endpoint to get harvester infomation.

**Reason** 
- As supernode owner I believe harvest infomation is important to them.
- Implement Harvester information on Symbol explorer.

**Route**
`/harvesters`
`/harvesters/{accountId}`

Example **HarvesterDTO** 
```
address : '9081FCCB41F8C8409A9B99E485E0E28D23BD6304EF7215E01A'
totalHarvestedBlocks :  100
totalHarvestedFees:  2300.000000
lastHarvestedBlock : '23410'
``` 

**Remark**
- Aggregating data for `/harvesters` queries may cost inefficient performance for rest endpoint, not sure using pagination will resolved the issue.

feedback are welcome.

**Comment by evias** [comment]
I think you can drop `harvestStatus` because it cannot be known by REST afaik.

**Comment by AnthonyLaw** [comment]
@evias thanks for input.

**Comment by rg911** [comment]
`Count`/ ` Top`queries can be quite expensive in Mongo. Unless the infrastructure of the node can cope with it otherwise won't recommend it.

**Comment by AnthonyLaw** [comment]
@rg911 I see, the PR #93 should be able to solve my problem, and thanks for the feedback.
