### ISSUE TITLE
anyOf keyword should be replaced with oneOf

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/symbol-openapi#11]
Several DTO uses the ``anyOf`` keyword when they should be using the ``oneOf`` keyword. The reason behind this intentional change allows us to generate code that compiles. At the current moment, most openapi-generators [do not support](https://github.com/OpenAPITools/openapi-generator/issues?q=oneOf+is%3Aopen) code generation with ``oneOf`` keyword.

[Rules of usage](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/), according to the docs:
* **anyOf**:  Validates the value against any (one or more) of the subschemas.
* **oneOf**: Validates the value against exactly one of the subschemas.

If you want to contribute to this issue, you can coordinate with the [openapi-generator community](https://github.com/OpenAPITools/openapi-generator/issues/634) to apply the necessary changes for better support of the OAS3 specific keywords.

**Comment by Vektrat** [comment]
couldn't this be used to manage optional params in favour of #19 ?
