### ISSUE TITLE
Single quotes in example values breaks auto-generated test cases

### ISSUE THREAD

**Issue by fullcircle23** [nemtech/symbol-openapi#112]
OpenAPI Generator for Python auto-generates fully formed test cases in Travis-CI. These tests revealed possible issues and/or room for improvements in the OpenAPI spec.

The first type of issue that broke several tests with `invalid syntax` error are the single quotes in example values. Screenshot of the errors (sample) in travis [job](https://travis-ci.org/github/fullcircle23/symbol-openapi-generator/jobs/672892623) log below or view the [raw log](https://api.travis-ci.org/v3/job/672892623/log.txt).

<img width="900" alt="image" src="https://user-images.githubusercontent.com/33846962/78881599-a07ee380-7a89-11ea-9312-83733e367348.png">

Examples of the OpenAPI spec that caused the error:

Example 1:
        maxTransactionsPerAggregate:
          type: string
          description: Maximum number of transactions per aggregate.
          example: **1'000**

Example 2:
        currencyMosaicId:
          type: string
          description: Mosaic id used as primary chain currency.
          example: **0x621E'C5B4'0385'6FC2**

The fix is to remove the single quotes in the example values.
1.) 1'000 is replaced with **1000**
2.) 0x621E'C5B4'0385'6FC2 is replaced with **0x621EC5B403856FC2**

Altogether, the `invalid syntax` errors were found in 12 test cases and the corresponding values (with some repeats) are as follows:

1. test_aggregate_network_properties_dto.py
    - max_transactions_per_aggregate = '1'000'
2. test_chain_properties_dto.py
    - currency_mosaic_id = '0x621E'C5B4'0385'6FC2'
3. test_hash_lock_network_properties_dto.py
    - locked_funds_per_aggregate = '10'000'000'
4. test_mosaic_network_properties_dto.py
    - max_mosaics_per_account = '10'000'
5. test_network_configuration_dto.py
    - currency_mosaic_id = '0x621E'C5B4'0385'6FC2'
6. test_plugins_properties_dto.py
    - max_transactions_per_aggregate = '1'000'
7. test_chain_properties_dto.py
    - harvesting_mosaic_id = '0x4291'ED23'000A'037A'
8. test_mosaic_network_properties_dto.py
    - max_mosaics_per_account = '10'000'
9. test_network_configuration_dto.py
    - harvesting_mosaic_id = '0x4291'ED23'000A'037A'
10. test_plugins_properties_dto.py
    - max_mosaics_per_account = '10'000'
11. test_chain_properties_dto.py
    - initial_currency_atomic_units = '8'998'999'998'000'000'
12. test_network_configuration_dto.py
    - initial_currency_atomic_units = '8'998'999'998'000'000'

As a workaround, I've added a script in existing [download-and-patch.sh](https://github.com/fullcircle23/symbol-openapi-generator/blob/feature/python-support/download-and-patch.sh) to fix the above values. I've also attached the openapi yml with and without the single quote fix patch for comparison:
[openapi3-any-of-patch.yml.txt](https://github.com/nemtech/symbol-openapi/files/4459796/openapi3-any-of-patch.yml.txt)
[openapi3-any-of-patch-single-quote-patch.yml.txt](https://github.com/nemtech/symbol-openapi/files/4459798/openapi3-any-of-patch-single-quote-patch.yml.txt)

@dgarcia360 I can also fix the above values in the spec files in this repo and remove the workaround patch. Please let me know. 

I'm also looking into the other [failed](https://travis-ci.org/github/fullcircle23/symbol-openapi-generator/jobs/673241300) test cases.

**Comment by dgarcia360** [comment]
@fullcircle23 The API returns the values with quotes like `0x621E'C5B4'0385'6FC2`, we'll have to skip the quotes somehow rather than remove them from the examples. Let's keep your patch so that you can advance with the development while we investigate how we can scape the quotes.

Could you please test if the Python generator does not complain if you wrap the affected examples with double quotes?

Example:

```
currencyMosaicId:
	type: string
	description: Mosaic id used as primary chain currency.
	example: "0x621E'C5B4'0385'6FC2"

**Comment by fullcircle23** [comment]
Thanks @dgarcia360. I'll test wrapping the affected examples with double quotes. 

Btw, which API "returns the values with quotes"?

**Comment by dgarcia360** [comment]
@fullcircle23  `/network/properties` endpoint from catapult-rest. You can check a response example here: http://api-01.us-west-1.symboldev.network:3000/network/properties

**Comment by fullcircle23** [comment]
@dgarcia360 Wrapping with double quotes worked on my local environment but not on travis. On travis (trusty), the openapi generator for python converted the double quotes to single quotes yielding incorrect syntax, for example: 
`max_transactions_per_aggregate = '1'000'`
whereas in my local (macOS), the single quotes were stripped:
`max_transactions_per_aggregate = '1000'`

Following are the same versions in both my local env and in travis:
- Python 3.6.3
- openapi-generator 4.2.3

Following are different:

OS
- local: macOS High Sierra
- travis: Ubuntu 14.04

pyenv
- local: 1.2.18
- travis: 1.1.5

There's a related openapi-generator [[BUG][PYTHON] Single quotes not escaped
](https://github.com/OpenAPITools/openapi-generator/issues/2808) but it's closed.

Spent a whole day on this including setting up my laptop with pyenv to have matching python versions and various other config changes but not getting very far.

Anyway, it seems like a bug still, probably related to the environment. So I've sent a request to travis-ci support to activate debug mode for the repository.

Meanwhile, I'm going to switch back to stripping the single quotes from those values.

**Comment by fullcircle23** [comment]
> @dgarcia360 Wrapping with double quotes worked on my local environment but not on travis. On travis (trusty), the openapi generator for python converted the double quotes to single quotes yielding incorrect syntax, for example:
> `max_transactions_per_aggregate = '1'000'`
> whereas in my local (macOS), the single quotes were stripped:
> `max_transactions_per_aggregate = '1000'`

I've managed to replicate the results in travis on my local env after fixing some issues in my local java environment. So I can confirm that string values with single quotes that are wrapped in double quotes ends up being wrapped in single quotes in the generated test files. I've found a bug in `openapi-generator` that caused this and will be raising an issue over there.

**Comment by fullcircle23** [comment]
I've fixed this issue in OpenAPITools/openapi-generator.  
Issue is https://github.com/OpenAPITools/openapi-generator/issues/5981.
Pending merge of PR https://github.com/OpenAPITools/openapi-generator/pull/6451.
