### ISSUE TITLE
Pagination - pagination property should not allow undefined

### ISSUE THREAD

**Issue by rg911** [nemtech/symbol-openapi#118]
In the new pagination refactoring spec, the `pagination` property is set to be optional which should be mandatory I think

**Comment by Vektrat** [comment]
you mean `page`?

**Comment by Vektrat** [comment]
you mean in the response? if so it should be mandatory yes, just like `data` should be mandatory as well

**Comment by rg911** [comment]
> you mean in the response? if so it should be mandatory yes, just like `data` should be mandatory as well

https://github.com/nemtech/symbol-openapi/blob/cc05b6fbcd5de49dbbdeb9831a5b03a3dfc10aa5/spec/core/transaction/schemas/TransactionPage.yml#L10

after the generation the `pagination` property is optional

**Comment by dgarcia360** [comment]
Thanks @rg911, fixed here https://github.com/nemtech/symbol-openapi/pull/117/files#diff-35c679f189e91934cc5706d9e9913fee
