### ISSUE TITLE
GenerationHash has been changed to GenerationHashSeed in NetworkProperties

### ISSUE THREAD

**Issue by rg911** [nemtech/symbol-openapi#123]
GenerationHash has been changed to GenerationHashSeed in NetworkProperties

https://github.com/nemtech/symbol-openapi/blob/9195d19c47c0efa626259ecc87464afef9383408/spec/core/network/schemas/NetworkPropertiesDTO.yml#L15

**Comment by Vektrat** [comment]
where has it changed exactly? we choose this name freely in REST and it isn't bound by any other schemas such as mongodb

we can update it for consistency, but i'd advise to delay this change until all the endpoint changes are in, so to avoid conflicts with the fork

**Comment by rg911** [comment]
isn't this from the server configuration ini file? Suppose the config name get changed? But agree to park it for now

**Comment by Vektrat** [comment]
this is in the config ini file yes, but the same string is in the `/node/info` results that we fetch from core, i'd expect consistency, but those can be two different changes... for the ini file we definitely need to update the openapi
