### ISSUE TITLE
Error types are missing from the transaction status type enum for 0.9.5.1

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-openapi#136]
New errors were added for the new transaction added in 0.9.5.1. the transaction status type enum needs to be updated. Below is one example.

https://github.com/nemtech/symbol-openapi/blob/2bb345f25def64585050b2209d4f80fa3c7bd267/spec/core/transaction/schemas/TransactionStatusTypeEnum.yml#L1

catapult_server0001.log:2020-05-19 23:38:59.580589 0x00007fc445ffb700: <warning> (chain::UtUpdater.cpp@160) dropping transaction 61D3415802FEE63086E95D0260A9B000CB6DA594A15FA65BB535DFD36847649F: Failure_Core_Link_Already_Exists
catapult_server0001.log:2020-05-19 23:38:59.586438 0x00007fc445ffb700: <warning> (subscribers::SubscriptionManager.cpp@101) rejected tx 61D3415802FEE63086E95D0260A9B000CB6DA594A15FA65BB535DFD36847649F due to result Failure_Core_Link_Already_Exists (deadline 16508338905)

**Comment by dgarcia360** [comment]
Blocked by https://github.com/nemtech/catapult-rest/issues/328
