### ISSUE TITLE
Add "status" to transaction payload

### ISSUE THREAD

**Issue by fboucquez** [nemtech/symbol-openapi#159]
ATM is not trivial to check the status of a transaction by just looking at the payload. The client and SDKs need to assume the value by checking at the metadata to see if there is a height or not (for example) or by knowing if the transaction was loading using a rest endpoint or another (like group: partial)  

https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/master/src/model/transaction/Transaction.ts#L300

https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/master/src/model/transaction/Transaction.ts#L314

https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/src/core/transactions/TransactionView.ts#L74

I would like to add a `status` to the transaction, probably inside the meta payloads like:

`meta: {status: partial | confirmed | unconfirmed | error?}`

Unsure if it makes sense to add it to embedded transactions too. I guess it does if embedded transactions are loaded as top-level search results.

**Comment by Vektrat** [comment]
this is kind of blocked by https://github.com/nemtech/catapult-rest/issues/372

**Comment by dgarcia360** [comment]
It made sense when /transactions were all under the same endpoint. Now, it might be redundant if REST provides different endpoints to request the transactions.

@fboucquez Do you still see the need to add ``status`` considering the latest pagination implementation?

**Comment by Vektrat** [comment]
it isn't needed because the transactions are already identifiable with this, closing this issue, because iirc core team also agreed with this
