### ISSUE TITLE
Missing "getTransactionsById" for partial and unconfirmed.

### ISSUE THREAD

**Issue by fboucquez** [nemtech/symbol-openapi#161]
At the moment, only confirmed transactions can be loaded by multiple ids.

https://github.com/nemtech/symbol-openapi/blob/master/spec/routes.yml#L67

Is it possible to use path (state/group) params in the getById methods? I don't think they are going to change.

**Comment by rg911** [comment]
it would be good to use path param for all transaction get and search I think
