### ISSUE TITLE
Document allow blocks to be sorted by height

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/symbol-openapi#162]
https://github.com/nemtech/catapult-rest/commit/b8535f56de7847df31ac9f9e89d957bf82816be1

**Comment by Vektrat** [comment]
i think this was already defined in the api

https://github.com/nemtech/symbol-openapi/blob/master/spec/core/block/schemas/BlockOrderByEnum.yml

**Comment by dgarcia360** [comment]
Nice :+1:, added the issue because I wasn't sure after reviewing the commit.
