### ISSUE TITLE
Allow loading one metadata by natural id

### ISSUE THREAD

**Issue by fboucquez** [nemtech/symbol-openapi#184]
Currently, you can only search for metadata returning pages. There is no way to load one particular metadata based on a natural id like with any other entity. We should have a method that returns single metadata from the metadata natural id or a 404 error 

The two options for natural id are:

1. CompositeHash: Users may not know it. We would need a way in the SDK to create the composite hash from key + type + source + target
2. Composite key like (key + type + source + target): It's too long and not user friendly. 

What do you prefer @rg911 @Vektrat @dgarcia360 ?

My preference would be 1, compositeHash. We need to create a hasher in the SDKs so users can create the Composite Hash if they just know the composite key values

**Comment by Vektrat** [comment]
has any client asked for this? or this is a suggestion just for consistency matters? do we know of any use cases or how clients would usually use/fetch metadata?
