### ISSUE TITLE
Remove totalPages and totalEntries from page payload

### ISSUE THREAD

**Issue by fboucquez** [nemtech/symbol-openapi#199]
To reflect the change on rest
https://github.com/nemtech/catapult-rest/issues/464

**Comment by Vektrat** [comment]
remember to update reference compatibility REST version to `v1.3.0` if such thing exists

**Comment by Vektrat** [comment]
also here: https://docs.symbolplatform.com/compatibility.html#compatibility-matrix

**Comment by Vektrat** [comment]
and here: https://github.com/nemtech/symbol-openapi/blob/main/CHANGELOG.md
