### ISSUE TITLE
HashLock vs LockHash

### ISSUE THREAD

**Issue by fboucquez** [nemtech/symbol-openapi#203]
Most objects are named HashLock
but some and routes are named LockHash

![image](https://user-images.githubusercontent.com/5390558/92290258-e67d8d80-eee9-11ea-8872-51c35a57a3d1.png)

Is it possible to unify the naming? What's the best one?

**Comment by segfaultxavi** [comment]
If they refer to the same object, I think they should be called the same (otherwise it is confusing!)
Regarding the best name, what IS this object? In English the adjective goes first and the noun later so, if this is a lock's hash, it should be called LockHash and if it's a hash's lock, then it should be called HashLock.

I am still out of context so please excuse me if I am completely off-mark :)

**Comment by fboucquez** [comment]
The way I see it, LockHash is the action, HashLock is the entity created from the action. Should it be then `searchHashLock`, `getHashLock` and `Hash lock routes`

This affects how the objects, methods, and API clients are generated. 

https://github.com/nemtech/symbol-openapi/blob/main/spec/plugins/lock_hash/routes/getLockHash.yml
https://github.com/nemtech/symbol-openapi/blob/main/spec/plugins/lock_hash/routes/searchLockHash.yml

@rg911 @Vektrat @martinayora any though? 

Do we have the same issue between `SecretLock` and `LockSecret`?

**Comment by Vektrat** [comment]
i don't really mind nor give much importance towards which naming is adopted or whether if it is in sync among the project's layers as long as it's clear to the end users

other than that, iirc in rest we are using the naming that core is using, unless it was updated at some point

**Comment by segfaultxavi** [comment]
The nomenclature seems also a bit confusing to me at the core level:
plugins/txes/**lock_hash**/src/plugins/**HashLock**Plugin.h

And the public docs too: https://docs.symbolplatform.com/serialization/lock_hash.html
And the same thing seems to happen with `SecretLock`.

Anyway, this is not related to REST so I won't pester you about it :)
At some point I will dig some more about it, though...
