### ISSUE TITLE
SecretHashAlgorithm should be changed back to LockHashAlgorithm

### ISSUE THREAD

**Issue by rg911** [nemtech/symbol-openapi#206]
Based on catbuffer definition.

https://github.com/nemtech/catbuffer/blob/085f070fdf018c692b015a3450aef6bbecfd2207/schemas/lock_secret/lock_secret_types.cats#L2

**Comment by rg911** [comment]
@fboucquez @Vektrat

**Comment by Vektrat** [comment]
i don't understand this issue, is this just a naming matter related to this? https://github.com/nemtech/symbol-openapi/issues/203

**Comment by rg911** [comment]
> i don't understand this issue, is this just a naming matter related to this? #203

yup. related, but just the algorithm enum name
