### ISSUE TITLE
IPv4 and IPv6 roles needs be added to openapi Node roles to match server.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-openapi#255]
IPv6 support was added to server and new Node roles were added.

https://github.com/nemtech/catapult-server/blob/3e0e0b26a26d68a4040f3dee7dd5c64acfc8679f/src/catapult/ionet/NodeRoles.cpp#L32

https://github.com/nemtech/catapult-server/blob/3e0e0b26a26d68a4040f3dee7dd5c64acfc8679f/src/catapult/ionet/NodeRoles.cpp#L32

**Comment by fboucquez** [comment]
The file https://github.com/nemtech/symbol-openapi/blob/main/spec/core/node/schemas/RolesTypeEnum.yml doesn't scale anymore. We need to convert the enum of all the combinations to a list of the 5. This is currently done at SDK level, we would need to update rest to return a list of numbers

**Comment by fboucquez** [comment]
I'm probably for 2 here. Convert to a number and explain how this number is a bitwise collection of the possible flags.
