### ISSUE TITLE
Mosaic nonce should be uint32

### ISSUE THREAD

**Issue by rg911** [nemtech/symbol-openapi#85]
re: https://github.com/nemtech/catbuffer/blob/master/schemas/mosaic/mosaic_types.cats#L1

**Comment by dgarcia360** [comment]
> There is no format uint32 in the OpenAPI spec: https://swagger.io/specification/#data-types
> Note that uint32 are in range between 0 to 4,294,967,295, where as int32 range varies between -2,147,483,648 to 2,147,483,647. To be able to represent all uint32 values, it's common to define the integer as int64 (-9223372036854775808 to 9223372036854775807).
