### ISSUE TITLE
Pagination refactor proposal

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/symbol-openapi#94]
Document new pagination approach https://github.com/nemtech/catapult-rest/issues/172 based on the conversations with the REST and SDK teams: 

- [x] Transaction Routes (base) #92 
- [x] Block Routes #93 
- [x] Account Routes #95 
- [x] Mosaic Routes #108
- [x] Namespace Routes #107
- [x] Receipt Routes #109
- [x] Metadata Routes #142
- [x] RestrictionAccount #193
- [x] RestrictionMosaic #193
- [x] Locks #187 and #188

**Comment by Vektrat** [comment]
all done
